// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package smartcatclient

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient(in *jlexer.Lexer, out *WorkflowStage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "progress":
			out.Progress = uint(in.Uint())
		case "stageType":
			out.StageType = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient(out *jwriter.Writer, in WorkflowStage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"progress\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.Progress))
	}
	{
		const prefix string = ",\"stageType\":"
		out.RawString(prefix)
		out.String(string(in.StageType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WorkflowStage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WorkflowStage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WorkflowStage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WorkflowStage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient(l, v)
}
func easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient1(in *jlexer.Lexer, out *Vendor) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "vendorAccountId":
			out.VendorAccountID = string(in.String())
		case "removedFromProject":
			out.RemovedFromProject = bool(in.Bool())
		case "cost":
			(out.Cost).UnmarshalEasyJSON(in)
		case "costDetailsFileId":
			out.CostDetailsFileID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient1(out *jwriter.Writer, in Vendor) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"vendorAccountId\":"
		out.RawString(prefix[1:])
		out.String(string(in.VendorAccountID))
	}
	{
		const prefix string = ",\"removedFromProject\":"
		out.RawString(prefix)
		out.Bool(bool(in.RemovedFromProject))
	}
	{
		const prefix string = ",\"cost\":"
		out.RawString(prefix)
		(in.Cost).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"costDetailsFileId\":"
		out.RawString(prefix)
		out.String(string(in.CostDetailsFileID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Vendor) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Vendor) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Vendor) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Vendor) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient1(l, v)
}
func easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient2(in *jlexer.Lexer, out *ProjectsList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(ProjectsList, 0, 0)
			} else {
				*out = ProjectsList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Project
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient2(out *jwriter.Writer, in ProjectsList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v ProjectsList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProjectsList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProjectsList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProjectsList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient2(l, v)
}
func easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient3(in *jlexer.Lexer, out *Project) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "accountId":
			out.AccountID = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "deadline":
			out.Deadline = string(in.String())
		case "creationDate":
			out.CreationDate = string(in.String())
		case "createdByUserId":
			out.CreatedByUserID = string(in.String())
		case "createdByUserEmail":
			out.CreatedByUserEmail = string(in.String())
		case "modificationDate":
			out.ModificationDate = string(in.String())
		case "sourceLanguageId":
			out.SourceLanguageID = uint64(in.Uint64())
		case "sourceLanguage":
			out.SourceLanguage = string(in.String())
		case "targetLanguages":
			if in.IsNull() {
				in.Skip()
				out.TargetLanguages = nil
			} else {
				in.Delim('[')
				if out.TargetLanguages == nil {
					if !in.IsDelim(']') {
						out.TargetLanguages = make([]string, 0, 4)
					} else {
						out.TargetLanguages = []string{}
					}
				} else {
					out.TargetLanguages = (out.TargetLanguages)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					v4 = string(in.String())
					out.TargetLanguages = append(out.TargetLanguages, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "status":
			out.Status = string(in.String())
		case "statusModificationDate":
			out.StatusModificationDate = string(in.String())
		case "domainId":
			out.DomainID = uint64(in.Uint64())
		case "clientId":
			out.ClientID = uint64(in.Uint64())
		case "vendors":
			if in.IsNull() {
				in.Skip()
				out.Vendors = nil
			} else {
				in.Delim('[')
				if out.Vendors == nil {
					if !in.IsDelim(']') {
						out.Vendors = make([]Vendor, 0, 0)
					} else {
						out.Vendors = []Vendor{}
					}
				} else {
					out.Vendors = (out.Vendors)[:0]
				}
				for !in.IsDelim(']') {
					var v5 Vendor
					(v5).UnmarshalEasyJSON(in)
					out.Vendors = append(out.Vendors, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "workflowStages":
			if in.IsNull() {
				in.Skip()
				out.WorkflowStages = nil
			} else {
				in.Delim('[')
				if out.WorkflowStages == nil {
					if !in.IsDelim(']') {
						out.WorkflowStages = make([]WorkflowStage, 0, 2)
					} else {
						out.WorkflowStages = []WorkflowStage{}
					}
				} else {
					out.WorkflowStages = (out.WorkflowStages)[:0]
				}
				for !in.IsDelim(']') {
					var v6 WorkflowStage
					(v6).UnmarshalEasyJSON(in)
					out.WorkflowStages = append(out.WorkflowStages, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "documents":
			if in.IsNull() {
				in.Skip()
				out.Documents = nil
			} else {
				in.Delim('[')
				if out.Documents == nil {
					if !in.IsDelim(']') {
						out.Documents = make([]Document, 0, 0)
					} else {
						out.Documents = []Document{}
					}
				} else {
					out.Documents = (out.Documents)[:0]
				}
				for !in.IsDelim(']') {
					var v7 Document
					(v7).UnmarshalEasyJSON(in)
					out.Documents = append(out.Documents, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "externalTag":
			out.ExternalTag = string(in.String())
		case "specializations":
			if in.IsNull() {
				in.Skip()
				out.Specializations = nil
			} else {
				in.Delim('[')
				if out.Specializations == nil {
					if !in.IsDelim(']') {
						out.Specializations = make([]string, 0, 4)
					} else {
						out.Specializations = []string{}
					}
				} else {
					out.Specializations = (out.Specializations)[:0]
				}
				for !in.IsDelim(']') {
					var v8 string
					v8 = string(in.String())
					out.Specializations = append(out.Specializations, v8)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "managers":
			if in.IsNull() {
				in.Skip()
				out.Managers = nil
			} else {
				in.Delim('[')
				if out.Managers == nil {
					if !in.IsDelim(']') {
						out.Managers = make([]string, 0, 4)
					} else {
						out.Managers = []string{}
					}
				} else {
					out.Managers = (out.Managers)[:0]
				}
				for !in.IsDelim(']') {
					var v9 string
					v9 = string(in.String())
					out.Managers = append(out.Managers, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "number":
			if in.IsNull() {
				in.Skip()
				out.Number = nil
			} else {
				in.Delim('[')
				if out.Number == nil {
					if !in.IsDelim(']') {
						out.Number = make([]string, 0, 4)
					} else {
						out.Number = []string{}
					}
				} else {
					out.Number = (out.Number)[:0]
				}
				for !in.IsDelim(']') {
					var v10 string
					v10 = string(in.String())
					out.Number = append(out.Number, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient3(out *jwriter.Writer, in Project) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"accountId\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"deadline\":"
		out.RawString(prefix)
		out.String(string(in.Deadline))
	}
	{
		const prefix string = ",\"creationDate\":"
		out.RawString(prefix)
		out.String(string(in.CreationDate))
	}
	{
		const prefix string = ",\"createdByUserId\":"
		out.RawString(prefix)
		out.String(string(in.CreatedByUserID))
	}
	{
		const prefix string = ",\"createdByUserEmail\":"
		out.RawString(prefix)
		out.String(string(in.CreatedByUserEmail))
	}
	{
		const prefix string = ",\"modificationDate\":"
		out.RawString(prefix)
		out.String(string(in.ModificationDate))
	}
	{
		const prefix string = ",\"sourceLanguageId\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.SourceLanguageID))
	}
	{
		const prefix string = ",\"sourceLanguage\":"
		out.RawString(prefix)
		out.String(string(in.SourceLanguage))
	}
	{
		const prefix string = ",\"targetLanguages\":"
		out.RawString(prefix)
		if in.TargetLanguages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.TargetLanguages {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.String(string(v12))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"statusModificationDate\":"
		out.RawString(prefix)
		out.String(string(in.StatusModificationDate))
	}
	{
		const prefix string = ",\"domainId\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.DomainID))
	}
	{
		const prefix string = ",\"clientId\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.ClientID))
	}
	{
		const prefix string = ",\"vendors\":"
		out.RawString(prefix)
		if in.Vendors == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v13, v14 := range in.Vendors {
				if v13 > 0 {
					out.RawByte(',')
				}
				(v14).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"workflowStages\":"
		out.RawString(prefix)
		if in.WorkflowStages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v15, v16 := range in.WorkflowStages {
				if v15 > 0 {
					out.RawByte(',')
				}
				(v16).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"documents\":"
		out.RawString(prefix)
		if in.Documents == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v17, v18 := range in.Documents {
				if v17 > 0 {
					out.RawByte(',')
				}
				(v18).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"externalTag\":"
		out.RawString(prefix)
		out.String(string(in.ExternalTag))
	}
	{
		const prefix string = ",\"specializations\":"
		out.RawString(prefix)
		if in.Specializations == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v19, v20 := range in.Specializations {
				if v19 > 0 {
					out.RawByte(',')
				}
				out.String(string(v20))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"managers\":"
		out.RawString(prefix)
		if in.Managers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v21, v22 := range in.Managers {
				if v21 > 0 {
					out.RawByte(',')
				}
				out.String(string(v22))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"number\":"
		out.RawString(prefix)
		if in.Number == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v23, v24 := range in.Number {
				if v23 > 0 {
					out.RawByte(',')
				}
				out.String(string(v24))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Project) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Project) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Project) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Project) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient3(l, v)
}
func easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient4(in *jlexer.Lexer, out *PatchProject) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "deadline":
			out.Deadline = string(in.String())
		case "clientId":
			out.ClientID = string(in.String())
		case "domainId":
			out.DomainID = uint64(in.Uint64())
		case "vendorAccountIds":
			if in.IsNull() {
				in.Skip()
				out.VendorAccountIDs = nil
			} else {
				in.Delim('[')
				if out.VendorAccountIDs == nil {
					if !in.IsDelim(']') {
						out.VendorAccountIDs = make([]string, 0, 4)
					} else {
						out.VendorAccountIDs = []string{}
					}
				} else {
					out.VendorAccountIDs = (out.VendorAccountIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v25 string
					v25 = string(in.String())
					out.VendorAccountIDs = append(out.VendorAccountIDs, v25)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "externalTag":
			out.ExternalTag = string(in.String())
		case "specializations":
			if in.IsNull() {
				in.Skip()
				out.Specializations = nil
			} else {
				in.Delim('[')
				if out.Specializations == nil {
					if !in.IsDelim(']') {
						out.Specializations = make([]string, 0, 4)
					} else {
						out.Specializations = []string{}
					}
				} else {
					out.Specializations = (out.Specializations)[:0]
				}
				for !in.IsDelim(']') {
					var v26 string
					v26 = string(in.String())
					out.Specializations = append(out.Specializations, v26)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "workflowStages":
			if in.IsNull() {
				in.Skip()
				out.WorkflowStages = nil
			} else {
				in.Delim('[')
				if out.WorkflowStages == nil {
					if !in.IsDelim(']') {
						out.WorkflowStages = make([]string, 0, 4)
					} else {
						out.WorkflowStages = []string{}
					}
				} else {
					out.WorkflowStages = (out.WorkflowStages)[:0]
				}
				for !in.IsDelim(']') {
					var v27 string
					v27 = string(in.String())
					out.WorkflowStages = append(out.WorkflowStages, v27)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient4(out *jwriter.Writer, in PatchProject) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"deadline\":"
		out.RawString(prefix)
		out.String(string(in.Deadline))
	}
	{
		const prefix string = ",\"clientId\":"
		out.RawString(prefix)
		out.String(string(in.ClientID))
	}
	{
		const prefix string = ",\"domainId\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.DomainID))
	}
	{
		const prefix string = ",\"vendorAccountIds\":"
		out.RawString(prefix)
		if in.VendorAccountIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v28, v29 := range in.VendorAccountIDs {
				if v28 > 0 {
					out.RawByte(',')
				}
				out.String(string(v29))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"externalTag\":"
		out.RawString(prefix)
		out.String(string(in.ExternalTag))
	}
	{
		const prefix string = ",\"specializations\":"
		out.RawString(prefix)
		if in.Specializations == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v30, v31 := range in.Specializations {
				if v30 > 0 {
					out.RawByte(',')
				}
				out.String(string(v31))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"workflowStages\":"
		out.RawString(prefix)
		if in.WorkflowStages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v32, v33 := range in.WorkflowStages {
				if v32 > 0 {
					out.RawByte(',')
				}
				out.String(string(v33))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PatchProject) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PatchProject) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PatchProject) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PatchProject) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient4(l, v)
}
func easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient5(in *jlexer.Lexer, out *Executive) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "assignedWordsCount":
			out.AssignedWordsCount = uint64(in.Uint64())
		case "progress":
			out.Progress = uint(in.Uint())
		case "supplierType":
			out.SupplierType = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient5(out *jwriter.Writer, in Executive) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"assignedWordsCount\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.AssignedWordsCount))
	}
	{
		const prefix string = ",\"progress\":"
		out.RawString(prefix)
		out.Uint(uint(in.Progress))
	}
	{
		const prefix string = ",\"supplierType\":"
		out.RawString(prefix)
		out.String(string(in.SupplierType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Executive) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Executive) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Executive) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Executive) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient5(l, v)
}
func easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient6(in *jlexer.Lexer, out *DocumentWorkflowStage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "progress":
			out.Progress = uint(in.Uint())
		case "wordsTranslated":
			out.WordsTranslated = uint64(in.Uint64())
		case "unassignedWordsCount":
			out.UnassignedWordsCount = uint64(in.Uint64())
		case "status":
			out.Status = string(in.String())
		case "executives":
			if in.IsNull() {
				in.Skip()
				out.Executives = nil
			} else {
				in.Delim('[')
				if out.Executives == nil {
					if !in.IsDelim(']') {
						out.Executives = make([]Executive, 0, 1)
					} else {
						out.Executives = []Executive{}
					}
				} else {
					out.Executives = (out.Executives)[:0]
				}
				for !in.IsDelim(']') {
					var v34 Executive
					(v34).UnmarshalEasyJSON(in)
					out.Executives = append(out.Executives, v34)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient6(out *jwriter.Writer, in DocumentWorkflowStage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"progress\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.Progress))
	}
	{
		const prefix string = ",\"wordsTranslated\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.WordsTranslated))
	}
	{
		const prefix string = ",\"unassignedWordsCount\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.UnassignedWordsCount))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"executives\":"
		out.RawString(prefix)
		if in.Executives == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v35, v36 := range in.Executives {
				if v35 > 0 {
					out.RawByte(',')
				}
				(v36).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DocumentWorkflowStage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DocumentWorkflowStage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DocumentWorkflowStage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DocumentWorkflowStage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient6(l, v)
}
func easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient7(in *jlexer.Lexer, out *Document) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "creationDate":
			out.CreationDate = string(in.String())
		case "deadline":
			out.Deadline = string(in.String())
		case "sourceLanguage":
			out.SourceLanguage = string(in.String())
		case "documentDisassemblingStatus":
			out.DisassemblingStatus = string(in.String())
		case "targetLanguage":
			out.TargetLanguage = string(in.String())
		case "status":
			out.Status = string(in.String())
		case "wordsCount":
			out.WordsCount = uint64(in.Uint64())
		case "statusModificationDate":
			out.StatusModificationDate = string(in.String())
		case "pretranslateCompleted":
			out.PretranslateCompleted = bool(in.Bool())
		case "workflowStages":
			if in.IsNull() {
				in.Skip()
				out.WorkflowStages = nil
			} else {
				in.Delim('[')
				if out.WorkflowStages == nil {
					if !in.IsDelim(']') {
						out.WorkflowStages = make([]DocumentWorkflowStage, 0, 1)
					} else {
						out.WorkflowStages = []DocumentWorkflowStage{}
					}
				} else {
					out.WorkflowStages = (out.WorkflowStages)[:0]
				}
				for !in.IsDelim(']') {
					var v37 DocumentWorkflowStage
					(v37).UnmarshalEasyJSON(in)
					out.WorkflowStages = append(out.WorkflowStages, v37)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "externalId":
			out.ExternalID = string(in.String())
		case "metaInfo":
			out.MetaInfo = string(in.String())
		case "placeholdersAreEnabled":
			out.PlaceholdersAreEnabled = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient7(out *jwriter.Writer, in Document) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"creationDate\":"
		out.RawString(prefix)
		out.String(string(in.CreationDate))
	}
	{
		const prefix string = ",\"deadline\":"
		out.RawString(prefix)
		out.String(string(in.Deadline))
	}
	{
		const prefix string = ",\"sourceLanguage\":"
		out.RawString(prefix)
		out.String(string(in.SourceLanguage))
	}
	{
		const prefix string = ",\"documentDisassemblingStatus\":"
		out.RawString(prefix)
		out.String(string(in.DisassemblingStatus))
	}
	{
		const prefix string = ",\"targetLanguage\":"
		out.RawString(prefix)
		out.String(string(in.TargetLanguage))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"wordsCount\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.WordsCount))
	}
	{
		const prefix string = ",\"statusModificationDate\":"
		out.RawString(prefix)
		out.String(string(in.StatusModificationDate))
	}
	{
		const prefix string = ",\"pretranslateCompleted\":"
		out.RawString(prefix)
		out.Bool(bool(in.PretranslateCompleted))
	}
	{
		const prefix string = ",\"workflowStages\":"
		out.RawString(prefix)
		if in.WorkflowStages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v38, v39 := range in.WorkflowStages {
				if v38 > 0 {
					out.RawByte(',')
				}
				(v39).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"externalId\":"
		out.RawString(prefix)
		out.String(string(in.ExternalID))
	}
	{
		const prefix string = ",\"metaInfo\":"
		out.RawString(prefix)
		out.String(string(in.MetaInfo))
	}
	{
		const prefix string = ",\"placeholdersAreEnabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.PlaceholdersAreEnabled))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Document) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Document) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Document) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Document) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient7(l, v)
}
func easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient8(in *jlexer.Lexer, out *Cost) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "value":
			out.Value = float64(in.Float64())
		case "currency":
			out.Currency = string(in.String())
		case "accuracyDegree":
			out.AccuracyDegree = string(in.String())
		case "detailsFileName":
			out.DetailsFileName = string(in.String())
		case "paymentStatus":
			out.PaymentStatus = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient8(out *jwriter.Writer, in Cost) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Value))
	}
	{
		const prefix string = ",\"currency\":"
		out.RawString(prefix)
		out.String(string(in.Currency))
	}
	{
		const prefix string = ",\"accuracyDegree\":"
		out.RawString(prefix)
		out.String(string(in.AccuracyDegree))
	}
	{
		const prefix string = ",\"detailsFileName\":"
		out.RawString(prefix)
		out.String(string(in.DetailsFileName))
	}
	{
		const prefix string = ",\"paymentStatus\":"
		out.RawString(prefix)
		out.String(string(in.PaymentStatus))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Cost) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Cost) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b166cadEncodeGithubComMarkus621GoSmartcatClient8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Cost) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Cost) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b166cadDecodeGithubComMarkus621GoSmartcatClient8(l, v)
}
